CREATE TABLE Users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid    VARCHAR(255),
    email    VARCHAR(255),
    username VARCHAR(255),
    password VARCHAR(255),
    active   BOOLEAN             DEFAULT TRUE                   NOT NULL,
    account_expired     BOOLEAN  DEFAULT FALSE                  NOT NULL,
    account_locked      BOOLEAN  DEFAULT FALSE                  NOT NULL,
    credentials_expired BOOLEAN  DEFAULT FALSE                  NOT NULL,
    role     VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);
ALTER TABLE users
    ADD CONSTRAINT uc_user_username UNIQUE (username);
